### ISSUE TITLE
Can content rows collapse?

### ISSUE THREAD

**Issue by yatil** [rachelandrew/cssgrid-ama#60]
The [codepen Example](http://codepen.io/yatil/pen/jBRpzq) shows five paragraphs. The container has `display:grid` and `grid-template-columns:  3fr 1fr`. By default, all children are 'grid-column: 1/2;'. Two paragraphs (the second and third) are set to `grid-column: 2 / -1`.

This creates a gap under the first paragraph. I’d hope for a technique that allows me to keep the “main” paragraphs close together (as if they were in a separate div), and still be able to position information that follows those main paragraphs “floating” in the sidebar.

Is this even possible?

**Comment by rachelandrew** [comment]
Grid is going to create a strict grid, so you can't have an empty cell in a row collapse if there is other stuff in that row.

If you play with the end row line you can get that sort of thing to work, by causing the sidebar to span multiple row tracks. However a grid stays in strict rows and columns. If there is any height that is going to carry right across the row.

http://codepen.io/rachelandrew/pen/KWYxMv

**Comment by yatil** [comment]
Thanks Rachel, that was not what I wanted to hear, but it’s good to know :-)

**Comment by rachelandrew** [comment]
I'm not really sure how else you would expect a grid to behave, if you have some use case that isn't solved by either flex or grid then that might be worth documenting for future spec development though.

**Comment by freshyill** [comment]
@yatil I know this is an ancient question, but I have the *exact* same use case! Glad to know I'm not alone.

Since I'm working on something pretty heavily art-directed, I'm able to solve the the problem by just adjusting the markup—see my [fork of your pen](https://codepen.io/freshyill/pen/oGxoNE). I didn't even need to change any styles there. Since I'm updating an old float-based project that will never, ever, change, I know this works for me. Your mileage may vary.

I eventually came to the same conclusion that Rachel explained above… CSS grid just doesn't work this way.

**Comment by yatil** [comment]
@freshyill That is obviously what works and is totally fine for most use cases. (And how I use it too, at the moment.) I have to document mine eventually, it is very specific but might be useful for others as well. :-)
