### ISSUE TITLE
start/end vs flex-start/flex-end

### ISSUE THREAD

**Issue by keithjgrant** [rachelandrew/cssgrid-ama#8]
In grid, the `justify-*` and `align-*` properties accept the values "start" and "end", but in flexbox, they accept "flex-start" and "flex-end".

Is this distinction intentional for some reason? Why not "grid-start" and "grid-end"? Or is there a plan for flexbox to support "start" and "end" at some point?

**Comment by rachelandrew** [comment]
My understanding is that `start` and `end` always align with the start or end edge. That is defined by the writing mode.

A flex container is different because it deals with both writing mode and flow direction. I think that is the basic distinction between the two. So the values are `flex-start` and `flex-end` for clarity.

The Box Alignment specification deals with the various layout methods individually as they all have different behaviours based on their nature.

**Comment by keithjgrant** [comment]
Ah, that makes sense. Thanks!
